### ISSUE TITLE
[BUG] fresh installed version

### ISSUE THREAD

**Issue by nixmomo** [easy-wi/developer#1324]
**Describe the bug**
First, a fresh installed webinterface is outdated and needs to be updated first.
Second. After Installing easy-wi webinterface and gameserver with your script, and added it the gameserver to webinterface, i try to install a game server but the serverlist is empty and i cant install anything
**To Reproduce**
follow your install instructions

**Expected behavior**
a working webinterface with possibility to add gameserver apps

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by AEon-Jan** [comment]
Did you installed a game on the master first?

**Comment by AEon-Jan** [comment]
![image](https://user-images.githubusercontent.com/31162382/159990098-e7a9fd8f-47a5-43cb-89af-b29999c635fc.png)
Use the ADD Button to add a game ...

**Comment by nixmomo** [comment]
![image](https://user-images.githubusercontent.com/8502506/160114298-ffdc9164-50df-46de-a57c-955d3df45665.png)
hmm ok i have not... how get i fixed this json issue?

**Comment by nixmomo** [comment]
Any Hints about this json error?

**Comment by Ballaual** [comment]
Issue still present! Fresh install (manually current dev version) on php8.2
